[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test/foundry"
cache_path = "forge-cache"
solc = "0.8.20"
evm_version = "shanghai"
optimizer = true 
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
