/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as timelockSol from "./Timelock.sol";
export type { timelockSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Senate } from "./Senate";
