/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as timelockSol from "./Timelock.sol";
export * as interfaces from "./interfaces";
export { Senate__factory } from "./Senate__factory";
