/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { Senate__factory } from "./Senate__factory";
export { Timelock__factory } from "./Timelock__factory";
