/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISenate__factory } from "./ISenate__factory";
export { ITimelock__factory } from "./ITimelock__factory";
